### ISSUE TITLE
do not crosspost

### ISSUE THREAD

**Issue by amborisov** [alisinfinite/journalpress#6]
Hello!
Suddenly, few days ago it ended crossposting to livejournal and to other mirrors. It says It can not connect to Livejournal.

**Comment by Kyleri** [comment]
Yeah, it's not crossposting to Dreamwidth any more either. Halp pls?

**Comment by annathepiper** [comment]
Hi, I'm not the creator of this code, but just in case anybody is still monitoring this thread, I discovered this doesn't actually appear to be an issue with the plugin.

It's an issue with Dreamwidth changing security settings on their end as per this post:

https://dw-dev.dreamwidth.org/221358.html

The workaround they describe for making the Semagic client work, i.e., making an API key, works for my local install of Journalpress.

Hope someone finds this helpful!

**Comment by Kyleri** [comment]
oooo YES, just did this & it totally worked, SO many thanks!

**Comment by annathepiper** [comment]
You're very welcome. LJ may also have implemented a similar API key thing, I dunno? I haven't tried to crosspost to LJ in ages. But it might be worth doublechecking on that side, anybody who's using the plugin to talk to LJ as well.
